### ISSUE TITLE
Update this project to use SvelteKit

### ISSUE THREAD

**Issue by bwklein** [yustarandomname/svelte-supabase-quickstart#2]
Is there a plan to migrate to SvelteKit for this example project?

**Comment by weepy** [comment]
What he said ^^

**Comment by bluepuma77** [comment]
This is the Way ^^

**Comment by Fahari** [comment]
I can't say more ^^

**Comment by Isaiah-Hamilton** [comment]
Supabase now has a sveltekit quickstart guide. Not sure if this is the answer to your issue, but hope that it helps. [Docs](https://supabase.com/docs/guides/with-sveltekit) and [Pull Request](https://github.com/supabase/supabase/pull/5118)

**Comment by abeldebruijn** [comment]
Closing this because official docs provides better support
